dependencies {
    implementation project(":nuvotifier-api")
    implementation platform('io.netty:netty-bom:4.2.18.Final')
    implementation 'io.netty:netty-handler'
    implementation 'io.netty:netty-transport-native-epoll::linux-x86_64'
    implementation 'com.google.code.gson:gson:2.14.0'
    testImplementation 'org.json:json:20260814'
    testImplementation 'com.google.guava:guava:33.7.1-jre'
}
